= .NET Core Backend Documentation

== Using The Sample .Net Backend

=== Run the Backend
* cd <path to netcore_api>
* dotnet run

=== Swagger Endpoint Documentation
* Once the backend is running go to this page to see all endpoints:
 - https://localhost:5001/swagger
 - <protocol>://localhost:<port>/swagger

== Creating a basic .NET Core Project
Run the following commands in a terminal and in the directory just above where you want dotnet to create your project.

=== create a new webapi project using dotnet CLI
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio-code

* dotnet new webapi -o <appname>

==== add packages to the app
* cd <appname>
* dotnet add package Microsoft.EntityFrameworkCore.SqlServer
* dotnet add package Microsoft.EntityFrameworkCore.InMemory

==== Running The Basic Backend
After installing the project template it comes with a template that we can use to test the basic .net app by opening the project in visual studio code and "run", ctrl+F5, or from CLI "dotnet run" in the application root. We should then be able to hit a sample api on a browser:
https://localhost:5001/WeatherForecast

==== Optional, add code generation packages "scaffolding"
* dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
* dotnet add package Microsoft.EntityFrameworkCore.Design
* dotnet tool install --global dotnet-aspnet-codegenerator

===== Generate Controllers
* dotnet aspnet-codegenerator controller -name <controllername> -async -api -m <modelname_to_control> -dc <database_context_name> -outDir <directory_name_to_output_controller>
 - dotnet aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers
 - dotnet aspnet-codegenerator controller -name StudentsController -async -api -m Student -dc SchoolContext -outDir Controllers
 - dotnet aspnet-codegenerator controller -name CoursesController -async -api -m Course -dc SchoolContext -outDir Controllers
 - dotnet aspnet-codegenerator controller -name EnrollmentsController -async -api -m Enrollment -dc SchoolContext -outDir Controllers

==== add authentication services
* https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-protect-backend-with-aad
* https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-custom-rest-api-netfw
* https://identityserver.io/

=== add OpenAPI/Swagger for endpoint documentation
In order to implement openapi/swagger we will utilize swashbuckle/Nswag, swagger document generators: 
https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&tabs=visual-studio-code

* dotnet add <cs_project_file_name> package Swashbuckle.AspNetCore -v 5.5.0
- dotnet add netcore_api.csproj package Swashbuckle.AspNetCore -v 5.5.0
* add swashbuckle as a service like normal
* when the server is up you can access swagger docs by:
- <protocol>://localhost:<port>/swagger/v1/swagger.json 
- <protocol>://localhost:<port>/swagger (UI)

=== add a database connection via Entity Framework
only use the setup database portion, we are not serving web pages, just an api server:
https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-3.1

==== Install the following packages to enable Entity Framework and Tools
* dotnet tool install --global dotnet-ef
 - installs entity framework cli tools
* dotnet add package Microsoft.EntityFrameworkCore.Design
 - installs entity framework design tools

==== create your models and dbcontext related
* your models should contain attribute and relational information
* the dbcontext should be a collection of your models

==== add new db context and configure dbcontext to use new db service
* add this into your startup.cs under configure services and add the new dbcontext to use your data source or database.
* this may require a connection string which can be configured in your appsettings.json
 - sample: "DefaultConnection": "Server=(localdb)\\mssqllocaldb;Database=netcore_api_db;Trusted_Connection=True;MultipleActiveResultSets=true"

==== initiate db based on models
* dotnet ef migrations add InitialCreate
 - The migrations command scaffolds a migration to create the initial set of tables for the model.
* dotnet ef database update
 - The database update command creates the database and applies the new migration to it.

= dotnet CLI Debugging
A collection of common debugging commands and tools.

== Common Commands
* dotnet restore
 - restores dotnet project items

